apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mesh-wl01
  namespace: gitapps
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.100.0.0/12"]
    pods:
      cidrBlocks: ["10.200.0.0/12"]
    serviceDomain: "cluster.local"
  topology:
    class: builtin-generic-v3.3.0 
    version: v1.32.0---vmware.6-fips-vkr.2
    controlPlane:
      replicas: 3
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-01
            #replicas: 2    # As we are using ClusterAutoScaler
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "2"
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
          variables:
            overrides:
              - name: vmClass
                value: k8s-worker-small
    variables:
      - name: vmClass
        value: k8s-master-small
      - name: storageClass
        value: vks-storage-policy
      - name: node
        value:
          labels:
            version: v1
            organization: engineering
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
          security:
            podSecurityStandard:
              audit: restricted
              auditVersion: latest
              enforce: privileged
              enforceVersion: latest
              warn: privileged
              warnVersion: latest
      - name: vsphereOptions
        value:
          persistentVolumes:
            availableStorageClasses:
              - vks-storage-policy
            defaultStorageClass: vks-storage-policy
      - name: volumes
        value:
          - name: containerd
            mountPath: /var/lib/containerd
            storageClass: vks-storage-policy
            capacity: 10Gi
          - name: kubelet
            mountPath: /var/lib/kubelet
            storageClass: vks-storage-policy
            capacity: 10Gi
      - name: osConfiguration
        value:
          ntp:
            servers:
              - ntp.broadcom.net
                #         trust:
                #additionalTrustedCAs:
                #- caCert:
                # secretRef:
                #  name: "indus-wl01-user-trusted-ca-secret"
                #  key: registry-cert
