apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mesh-wl
  namespace: mesh
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.100.0.0/12"]
    pods:
      cidrBlocks: ["10.200.0.0/12"]
    serviceDomain: "cluster.local"
  topology:
    class: builtin-generic-v3.4.0
    classNamespace: vmware-system-vks-public
    version: v1.33.1---vmware.1-fips-vkr.2
    controlPlane:
      replicas: 3
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: "os-name=ubuntu,os-version=24.04"
    workers:
      machineDeployments:
      - class: node-pool
        name: node-pool-01
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
            run.tanzu.vmware.com/resolve-os-image: "os-name=ubuntu,os-version=24.04"
        strategy:
          remediation:
            maxInFlight: 20%                   # See details for more info
          rollingUpdate:
            deletePolicy: Random               # Allowed values - "Random, "Newest", "Oldest"
            maxSurge: 1
            maxUnavailable: 0
          type: RollingUpdate                  # Allowed values - RollingUpdate and OnDelete
        variables:
          overrides:
            - name: vmClass
              value: k8s-worker
    variables:
    - name: kubernetes
      value:
        certificateRotation:
          enabled: true
          renewalDaysBeforeExpiry: 90
        security:
          podSecurityStandard:
            audit: restricted                            # OPTIONAL, enum: "", privileged, baseline, restricted
            auditVersion: latest                         # OPTIONAL, e.g., "v1.31"
            enforce: restricted                          # OPTIONAL, enum: "", privileged, baseline, restricted
            enforceVersion: latest                       # OPTIONAL, e.g., "v1.31"
            warn: restricted                             # OPTIONAL, enum: "", privileged, baseline, restricted
            warnVersion: latest                          # OPTIONAL, e.g., "v1.31"
#            deactivated: false                           # OPTIONAL, default: false
#            exemptions:
#              namespaces: []
    - name: vmClass
      value: k8s-master
    - name: storageClass
      value: vks-storage-policy
    - name: node
      value:
        labels:
          tenant: customer0
          organization: engineering
    - name: vsphereOptions
      value:
        persistentVolumes:
          availableStorageClasses:
            - vks-storage-policy
          defaultStorageClass: vks-storage-policy
    - name: volumes
      value:
        - name: containerd
          mountPath: /var/lib/containerd
          storageClass: vks-storage-policy
          capacity: 10Gi
        - name: kubelet
          mountPath: /var/lib/kubelet
          storageClass: vks-storage-policy
          capacity: 10Gi
    - name: osConfiguration
      value:
        ntp:
          servers:
            - ntp.broadcom.net
        sshd:
          banner: "Security Warning Accessing the mesh-wl cluster"
#       trust:
#         additionalTrustedCAs:
#         - caCert:
#             secretRef:
#               name: "indus-wl01-user-trusted-ca-secret"
#               key: registry-cert
#         - caCert:
#             content: |-
#               ------BEGIN CERTIFICATE-----
#               MII.....
#               EXJHDJKSDsd
#               MII.....
#               ------END CERTIFICATE-----
