#  base64 -w 0 /etc/docker/certs.d/registry.corp.internal:8888/registry.corp.internal.cert | base64 -w 0

apiVersion: v1
data:
  registry-cert: TFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVZEVha05EUVM5aFowRjNTVUpCWjBsVldtVXlWazFGYjBWbVkySjNXalZKVW04d05tMU1aMGt2VFhOamQwUlJXVXBMYjFwSmFIWmpUa0ZSUlU0S1FsRkJkMk42UlV4TlFXdEhRVEZWUlVKb1RVTlJNRFI0UkdwQlRVSm5UbFpDUVdkTlFsVnNkVnBIYkdoTlVUUjNSRUZaUkZaUlVVaEVRVlpLWW0xU2NBcFpWRVZSVFVFMFIwRXhWVVZEWjNkSVdsaG9hR0pZUW5OYVZFVlNUVUU0UjBFeFZVVkRkM2RKVlVkV2VXTXlPWFZaVjNkNFNIcEJaRUpuVGxaQ1FVMU5Da1p1U214YU1teDZaRWhLTlV4dFRuWmpia0YxWVZjMU1GcFlTblZaVjNkM1NHaGpUazFxVVhoTlJFRXlUVlJGZVU1VVVUQlhhR05PVFhwUmVFMUVRVEFLVFZSRmVVNVVVVEJYYWtKNlRWRnpkME5SV1VSV1VWRkhSWGRLUkZScVJVOU5RWGRIUVRGVlJVTkJkMFpUVnpWcllWZEZlRVJxUVUxQ1owNVdRa0ZqVFFwQ1ZXeDFXa2RzYUUxU1FYZEVaMWxFVmxGUlMwUkJaR3hsUjBaMFkwZDRiRTFTUlhkRWQxbEVWbEZSVEVSQmFGRmFXRXA2WWpJMWFHSkVSV1pOUWpCSENrRXhWVVZCZDNkWFkyMVdibUZZVGpCamJtdDFXVEk1ZVdORE5YQmlibEpzWTIwMWFHSkVRME5CYVVsM1JGRlpTa3R2V2tsb2RtTk9RVkZGUWtKUlFVUUtaMmRKVUVGRVEwTkJaMjlEWjJkSlFrRktaRkpxUjNCU2EzSldSMnhJYjA5NWExWlNjRkoyWVdjeWJHcFNNMVpaY0hGU1YxaERVMnREV0ZrMUsyUkZTQXBKYjBscldqWllTRTVXUldaT1RHTTFNbkYxYnprMFMwcFlOa0k0YVdGaWVVNXNaM2RwVlRRMlowSmlTMkV6ZW5odU1tWlNlamsyYVU0eVNHbDVNRVZQQ2xoWkwxVlJWazVaU2tkR1JtSjJkMU42VHpCTlZteDVVazk2Y1RSMWFVNHlPRE5OTjJSVU5tcHdOV3hYY1ZOdVpWUnpSbUo0V0hSQ1pHMUJVVkJFTmxBS2RtOW9WR1J0WW5RNFQzcHhUVlIxU2xWa1VtcFdaMDFRZVZWNlpVSjRNelZvT1VWMVYyVk5hMHg1U1daRWJFdzFSRUpwY1ZSVkwwTldjRmRpZDBwWmF3cE5OVE55VEVwNVVuaHdaemhzU1haUFkwWjNja0Z2WXpkNVlrSmFOSGxQVVdkME9VMVphV3h0VFdoSU5IQjRTemQ0ZWxsbk1uWlRWRUpsWlM5MGNsZGlDbXMzUW0xUFZuZzRhSHBTVEhOV1IwZHpaWEl3WVV4RFZYcFlUMHhPV0hoM2JFOUlLMjlzTDJWQ1oweHNZMlJzVEZOVVdDOU9XRTVsUlZSNlprZHlXRzRLUXl0dk1XMWhPRFpNTW5jeldrWXhRblpLY2xkVmR6aHVhREJpUW5BMFkxZHpUMXBoUlN0emFGUjNRa2wwUVVsQlIzZEpRVTlwYnpaUlNWazVSSE5FU2dwbE1XWkZaa2xxUVdFMVRVOXNUVm95TW5aaGVGQnlOeXR6T1c5elFtTlFTR2QxV0hkNVUzRjFkRGxhYVdoVk0xTjJPR0pSVW1kdFZEUjFiemMwY1ZkV0NpOXpaVk5KYUhwQmFUazVka2RFYVhWcVZXMHlaV2hMZEVoMlZWSmtkRlp1YWpWNFpsTkRkbUV5THpjeFpreEhRVGRvZDJGc1VFNUVTRXBpSzJoMWJtd0tSbkUwUTJweVNWSkhRemQ1T0U4MFpuRkdWbEptU1RScGF6YzNNWGM0ZVRJNWNuUmFjemhqTVdKR1IwWk9jMjVpVUVaa09ISmFNVTV0VldNd01WVkxRZ3BPTWt0eGNHZ3JkbTlJUmtVMlVrb3pSWEJoU1RGSWExQlBURUp2UlhwTmRETjRWVUpDUWpCS2VrUk5TalZ3T0ZSNk1Hd3ZlRUZHY1hWV2JGUkJaMDFDQ2tGQlIycG5XbXQzWjFwWmQwaDNXVVJXVWpCcVFrSm5kMFp2UVZWQmVtWnhVVEJLZWpsYVNDOW1Sa3hCUkhOWE1ubENhRkZrZWtGM1ExRlpSRlpTTUZRS1FrRkpkMEZFUVV4Q1owNVdTRkU0UlVKQlRVTkNVRUYzUlhkWlJGWlNNR3hDUVhkM1EyZFpTVXQzV1VKQ1VWVklRWGRGZDBwM1dVUldVakJTUWtOQmR3cEliMGxYWTIxV2JtRllUakJqYm10MVdUSTVlV05ETlhCaWJsSnNZMjAxYUdKSlkwVnlRa0ZMV2tSQlpFSm5UbFpJVVRSRlJtZFJWVm8yYm00cmExUnZDbkZPU0hWTU9Xd3pZVUp1TVZkcVFtdHFOV3QzUkZGWlNrdHZXa2xvZG1OT1FWRkZUa0pSUVVSblowbENRVU5KYjNneFJFcDNOMUpxWlRGQ2VsQXlXamtLU2pscVZHeDZRblpNYVU0clQyNUpWRFZzTUhsR01WbEdOMUZhVjNJNGVrczBXVU5TVlcxWGFXNUtXVnBwT1ZCVlJERndPQzlXU2taTVdFNTFjR3B6TWdwb04zTlRjbEJUVmpsaWNuZHdUVUp5VkhJdlExbHlRbFF3ZFZsSVVFc3lhRVZJVTBRcldsazRWRU5CYldkbEsyVXJSMUIxU1VWTk4xSmFRMkVyTm14VENrbDZRa05yZFNzcmVIaDFWRGxTVEc0M2RURkVRWE0yWlZoMWRGVkxUbEE0ZEdsUWFFcFVaM1pQTkdaSVdtRk1UVXBzUzNKMk9IcFhhbXhxTm1OQmRGb0thMEZtUjJwVFJXRk9WRU5ZVDJwTWJGRjBWRmxPZWl0Mk1qUlVZWEF3UlZSaFZtTlhWbXBFVEhGbGQycHFNbUZNYWt0d01teGFaRGhYU1hOcFJXWXdVUXBQUW1WeUswUm9UR3czTkVKaFdFTmtNVEYxZVZoQmVIaHpZV0pRYVdwWU1raEZjV3BXTTIxNFFuWTBRMEY0T1RaRUx5OWFabGhhU0dGU1FYQndWMU0yQ2s1d2FUSnVXbEJIV2pNd1JWRXdXa2xzVm5KT01WVkxkMjlNU0RkRWVtNXFRMDUwYW0xbE1GVlJZbXRSU2t0QmNVVTNTVlY2Tlhkd1lsSkZWVk51YVRBS05GcFZaM1pyY0ZsMGMwSlpVMDB5YzBwaGFVSlVZbXhSZUV0eFVFWndSblI0ZDNSV2NWQTFkRnB5TjBoVVJtcHpZMGxPVmtFMGFEUkZNVFZSYkZKTFlncFhNblpXYzJaSVJVMVZaV041WTNWV1MxbHFUR2x0UkRKbWEzUnNUVEpLUzNoT1NqSkRPR2RvWTNsNFZuaExUbTFwU1ZJeGVqSlFjR2xGYzBJeVozQnRDbWhYVlRCck9GRnFjSEo1Unk5Sk5URk9RVEEwYVZKdE9GRjZhemh3UWpKcU1sVkpkRE14WWxOSk1qSlVZMGN6YkhWV01uUmFWSGhsYlZCTmVXMUJhM01LTVdKUGVVbG1OVFp6SzA4MlQyczFiMVZ1ZEVwclJXMDFZbnAwYzJWa01FSk1hRGRYTjAwM1ZXNUZSMFpqT1Zad1JHWlBWbWhGTVdaV05WUkRTREpOVHdwNGRHb3JielowTmpRdlpETk1ReXRsYjFSQldtcDJaRWtLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89
kind: Secret
metadata:
  name: indus-wl01-user-trusted-ca-secret
  namespace: indus-shop
type: Opaque

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: indus-wl01
  namespace: indus-shop
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.100.0.0/12"]
    pods:
      cidrBlocks: ["10.200.0.0/12"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.30.1---vmware.1-fips-tkg.5
    controlPlane:
      replicas: 3
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-01
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
          variables:
            overrides:
              - name: vmClass
                value: k8s-worker
    variables:
      - name: vmClass
        value: k8s-master
      - name: storageClass
        value: k8s-storage-policy
      - name: defaultStorageClass
        value: k8s-storage-policy
      - name: ntp
        value: ntp.broadcom.net
      - name: podSecurityStandard
        value:
          enforce: "baseline"
      - name: trust
        value:
          additionalTrustedCAs:
            - name: registry-cert
