apiVersion: v1
kind: Service
metadata:
  name: activeapps-svc
  namespace: activeapps
  labels:
    app: activeapps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: activeapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activeapps
  namespace: activeapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: activeapps
  template:
    metadata:
      labels:
        app: activeapps
    spec:
      containers:
      - name: activeapps
        image: paulbouwer/hello-kubernetes:1.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: activeapps-httpproxy
  namespace: activeapps
  labels:
    app: activeapps
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: activeapps.corp.internal
    tls:
      secretName: activeapps-ingress-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: activeapps-svc
          port: 80
