apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tkg.vsphere.vmware.com.3.2.0
  annotations:
    appplatform.vmware.com/compatibility-check_service: upgrade-compatibility-service
    appplatform.vmware.com/compatibility-check_port: "80"
    appplatform.vmware.com/compatibility-check_protocol: https
    appplatform.vmware.com/compatibility-check_url: ucs/v2/compatibility
    appplatform.vmware.com/compatibility-check_method: POST
    appplatform.vmware.com/compatibility-check_ca_secret: ucs-service-ca-cert
    appplatform.vmware.com/required_capability.0: TKG_SupervisorService_Supported
    appplatform.vmware.com/compatibility-check_data: |
      [
        {
          "version": "v1",
          "requires": {
            "tanzu-kubernetes-release": [
              {
                "#data_object_or_protocol": "data object",
                "predicate": {
                  "operation": "not",
                  "arguments": [
                    {
                      "operation": "isVersionSatisfied",
                      "arguments": {
                        "initiator": "vmware.com/gccontroller",
                        "receiver": "ovf",
                        "versions": [
                          "v1.18.10+vmware.1-tkg.1.3a6cd48",
                          "v1.18.15+vmware.1-tkg.1.600e412",
                          "v1.18.15+vmware.1-tkg.2.ebf6117",
                          "v1.18.19+vmware.1-tkg.1.17af790",
                          "v1.18.19+vmware.1-tkg.1.19c0a5e",
                          "v1.18.5+vmware.1-tkg.1.c40d30d",
                          "v1.17.17+vmware.1-tkg.1.d44d45a",
                          "v1.17.13+vmware.1-tkg.2.2c133ed",
                          "v1.17.11+vmware.1-tkg.2.ad3d374",
                          "v1.17.11+vmware.1-tkg.1.15f1e18",
                          "v1.17.8+vmware.1-tkg.1.5417466",
                          "v1.16.14+vmware.1-tkg.1.ada4837",
                          "v1.16.12+vmware.1-tkg.1.da7afe7",
                          "v1.16.8+vmware.1-tkg.3.60d2ffd"
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          },
          "offers": {
            "PersistentVolumeClaim": {
              "versions": {
                "k8s.io/kubernetes": [
                  "core/v1"
                ]
              }
            },
            "VirtualMachine": {
              "versions": {
                "k8s.io/kubernetes": [
                  "vmoperator.vmware.com/v1alpha1"
                ]
              }
            },
            "CnsVolumeMetadata": {
              "versions": {
                "hatchway.vmware.com/vspherecsidriver": [
                  "cns.vmware.com/v1alpha1"
                ]
              }
            },
            "k8s.io/secret": {
              "versions": {
                "k8s.io/kubernetes": [
                  "core/v1"
                ]
              }
            },
            "k8s.io/configmap": {
              "versions": {
                "k8s.io/kubernetes": [
                  "core/v1"
                ]
              }
            },
            "VirtualMachineService": {
              "versions": {
                "vmware.com/vmoperator": [
                  "vmoperator.vmware.com/v1alpha1"
                ]
              }
            },
            "TKGSvS": {
              "versions": {
                "vmware.com/gccontroller": [
                  "3.0.0",
                  "3.1.0",
                  "3.2.0"
                ]
              }
            },
            "TKGController": {
              "versions": {
                "vmware.com/gccontroller": [
                  "3.7",
                  "3.8",
                  "3.9",
                  "3.10"
                ]
              }
            }
          }
        }
      ]
    supportbundler.vmware.com/manifest: tkgs-support-bundler-cm
spec:
  refName: tkg.vsphere.vmware.com
  version: 3.2.0
  kubernetesVersionSelection:
    constraints: '>=1.26.0'
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harborsupervisor.corp.internal/supervisor-images/tkg-service:3.2.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        cpVMSize:
          type: string
          description: cpVMSize indicates the capacity of the Supervisor Control Plane. It's derived from Supervisor's tshirt size.
          default: LARGE
        ssoDomain:
          type: string
          description: ssoDomain indicates the name of the default SSO domain configured in vCenter.
          default: vsphere.local
        networkProvider:
          type: string
          description: networkProvider indicates the Network Provider used on Supervisor. (e.g. NSX or vsphere-network)
          default: NSX
        tmcNamespace:
          type: string
          description: tmcNamespace indicates the namespace used for TMC to be deployed.
          default: tmc-svc-namespace
        namespacesCLIPluginVersion:
          description: namespacesCLIPluginVersion indicates the Supervisor recommended namespaces CLIPlugin CR version.
          type: string
          default: v1.0.0
        vcPublicKeys:
          type: string
          description: vcPublicKeys indicates the base64 encoded vCenter OIDC issuer, client audience and the public keys in JWKS format.
          default: a2V5cw==
          contentEncoding: base64
        podVMSupported:
          type: boolean
          description: podVMSupported indicates if the Supervisor supports PodVMs.
          default: false
        stretchedSupervisor:
          type: boolean
          description: This field indicates whether the environment is a Stretched Supervisor
          default: false
        cloudVC:
          type: boolean
          description: cloudVC indicates if the vCenter is deployed on cloud.
          default: false
        controlPlaneCount:
          type: integer
          description: The value indicates the number of control planes enabled on the Supervisor.
          default: 3
        capabilities:
          deprecated: true
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: boolean
            required:
            - name
            - value
        capabilitiesStatus:
          type: object
          properties:
            services:
              additionalProperties:
                additionalProperties:
                  properties:
                    activated:
                      type: boolean
                  required:
                  - activated
                  type: object
                type: object
              type: object
            supervisor:
              additionalProperties:
                properties:
                  activated:
                    type: boolean
                required:
                - activated
                type: object
              type: object
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tkg.vsphere.vmware.com
spec:
  displayName: Kubernetes Service
  longDescription: Kubernetes Service is a turnkey solution for deploying, running, and managing enterprise-grade Kubernetes clusters for hosting applications on Supervisor.
  shortDescription: Cluster management
  providerName: VMware
  maintainers:
  - name: ""
  categories:
  - cluster management
