apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    velero.io/change-image-name: RestoreItemAction
    velero.io/plugin-config: ""
  name: change-image-name-config-modifier # Dont change this name
  namespace: velero
data:
  case1: 10.158.128.62,10.158.128.57
