apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argoapps
  namespace: argocd-application
  labels:
    owner: argo
spec:
  nodePlacement:
    nodeSelector:
      kubernetes.io/os: CRX
  server:
    host: argocdapps.corp.internal
    service:
      type: LoadBalancer
