apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argoapps
  namespace: svc-argocd-operator-domain-c1007
  labels:
    example: demo
spec:
  nodePlacement:
    nodeSelector:
      kubernetes.io/os: CRX
  server:
    insecure: true        
